### ISSUE TITLE
Call to undefined method Akeneo\Pim\ApiClient\AkeneoPimClient::listPerPage()

### ISSUE THREAD

**Issue by dev-kv** [akeneo/magento2-connector-community#650]
**Environment and configuration**

1. Magento ver. 2.4.4
2. akeneo/module-magento2-connector-community 103.4.3
3. akeneo version: 6.0 CE

**Steps to reproduce**

1. In Akeneo connector configuration, update with Last X days updated=1
2. Do the product sync from akeneo to magento with /usr/local/bin/php /home/magento/public_html/bin/magento akeneo_connector:import --code=product
3. Start product import job

**Expected result**

1. Products are imported successfully with last X days updated=1

**Actual result**

1. Import throws critical error and freezes in "processing" state.
/usr/local/bin/php /home/magento/public_html/bin/magento akeneo_connector:import --code=product
[10:03:37] Start import
[10:03:37] Import ID : 64941c791b98e
[10:03:37] Create temporary table
Call to undefined method Akeneo\Pim\ApiClient\AkeneoPimClient::listPerPage()#0 /home/magento/public_html/vendor/akeneo/module-magento2-connector-community/Executor/JobExecutor.php(556): Akeneo\Connector\Job\Product->createTable()
#1 /home/magento/public_html/vendor/akeneo/module-magento2-connector-community/Executor/JobExecutor.php(451): Akeneo\Connector\Executor\JobExecutor->executeStep()
#2 /home/magento/public_html/vendor/akeneo/module-magento2-connector-community/Executor/JobExecutor.php(349): Akeneo\Connector\Executor\JobExecutor->run('archiefkasten')
#3 /home/magento/public_html/generated/code/Akeneo/Connector/Executor/JobExecutor/Proxy.php(119): Akeneo\Connector\Executor\JobExecutor->execute('product', Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /home/magento/public_html/vendor/akeneo/module-magento2-connector-community/Console/Command/AkeneoConnectorImportCommand.php(98): Akeneo\Connector\Executor\JobExecutor\Proxy->execute('product', Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /home/magento/public_html/vendor/symfony/console/Command/Command.php(255): Akeneo\Connector\Console\Command\AkeneoConnectorImportCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /home/magento/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /home/magento/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Akeneo\Connector\Console\Command\AkeneoConnectorImportCommand\Interceptor->___callParent('run', Array)
#8 /home/magento/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Akeneo\Connector\Console\Command\AkeneoConnectorImportCommand\Interceptor->Magento\Framework\Interception\{closure}(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /home/magento/public_html/generated/code/Akeneo/Connector/Console/Command/AkeneoConnectorImportCommand/Interceptor.php(23): Akeneo\Connector\Console\Command\AkeneoConnectorImportCommand\Interceptor->___callPlugins('run', Array, Array)
#10 /home/magento/public_html/vendor/symfony/console/Application.php(1021): Akeneo\Connector\Console\Command\AkeneoConnectorImportCommand\Interceptor->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /home/magento/public_html/vendor/symfony/console/Application.php(275): Symfony\Component\Console\Application->doRunCommand(Object(Akeneo\Connector\Console\Command\AkeneoConnectorImportCommand\Interceptor), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /home/magento/public_html/vendor/magento/framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /home/magento/public_html/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /home/magento/public_html/bin/magento(23): Symfony\Component\Console\Application->run()
#15 {main}

I tried this change, seem to be not fixed the problem:
- $productModels = $akeneoClient->listPerPage(1, false, $filter);
+ $productModels = $akeneoClient->getProductModelApi()->listPerPage(1, false, $filter);

**Comment by madleen** [comment]
Hey @dev-kv, 
With the latest version of the module, there are no more problems. 
Thanks to the proofreaders 🙏 
Mado

**Comment by cengizcoskun** [comment]
Hi,

I tried with version 103.5.0 but the problem still persists.
